const fs = require("fs");

const generateTailoredResume = async (
  originalResume,
  jobTitle,
  skills
) => {

  const tailoredResume = `
==================================
AI TAILORED RESUME
==================================

Candidate Resume Optimized For:
${jobTitle}

----------------------------------
KEY SKILLS
----------------------------------

${skills.join(", ")}

----------------------------------
SUMMARY
----------------------------------

Highly motivated software engineer
with strong experience in modern
web technologies and AI systems.

Optimized specifically for:
${jobTitle}

----------------------------------
TECHNICAL STACK
----------------------------------

React.js
Node.js
MongoDB
Express.js
JavaScript
AI Automation
Machine Learning

----------------------------------
PROJECTS
----------------------------------

1. AI Resume Analyzer
2. Job Auto Apply System
3. AI Tailored Resume Generator

----------------------------------
Generated By:
HireFlow AI System
----------------------------------
`;

  const fileName =
    `tailored_${Date.now()}.txt`;

  fs.writeFileSync(
    `uploads/${fileName}`,
    tailoredResume
  );

  return fileName;
};

module.exports = {
  generateTailoredResume,
};